---
kind: pipeline
name: molecule

environment:
  MOLECULE_IMAGES: >
    geerlingguy/docker-ubuntu1604-ansible
    geerlingguy/docker-ubuntu1804-ansible
    geerlingguy/docker-ubuntu2004-ansible
    geerlingguy/docker-debian9-ansible
    geerlingguy/docker-debian10-ansible

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
      - name: sysfs
        path: /sys/fs/cgroup

volumes:
  - name: dockersock
    temp: {}
  - name: sysfs
    host:
      path: /sys/fs/cgroup

steps:
  - name: Lint
    image: veselahouba/molecule
    commands:
      - shellcheck_wrapper
      - flake8
      - yamllint .
      - ansible-lint

  - name: Molecule test
    image: veselahouba/molecule
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
      - name: sysfs
        path: /sys/fs/cgroup
    commands:
      - sleep 5
      - docker ps -a
      - ansible --version
      - molecule --version
      # Loop instead of matrix
      - |
        for MOLECULE_IMAGE in $${MOLECULE_IMAGES}; do
          export MOLECULE_IMAGE
          molecule test --all
        done

  - name: Slack notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: ci-cd
      template: >
        Molecule for `{{build.branch}}` failed.
        {{build.link}}
    when:
      status:
        - failure
---
kind: pipeline
name: release
depends_on:
  - molecule
trigger:
  event:
    - tag
steps:
  - name: Publish
    image: veselahouba/molecule
    environment:
      GALAXY_API_KEY:
        from_secret: GALAXY_API_KEY
    commands:
      - >
        ansible-galaxy role import --api-key $${GALAXY_API_KEY}
        $${DRONE_REPO_OWNER} $${DRONE_REPO_NAME}

  - name: Slack notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: ci-cd
      template: >
        {{#success build.status}}
          Publish for `{{build.tag}}` succeeded.
          {{build.link}}
        {{else}}
          Publish for `{{build.tag}}` failed.
          {{build.link}}
        {{/success}}
    when:
      status:
        - success
        - failure
